#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    // Literals
    Identifier,
    StrLiteral,
    CharLiteral,
    NumLiteral,

    // keywords
    AsKeyword,
    AsyncKeyword,
    AwaitKeyword,
    BreakKeyword,
    CaseKeyword,
    CatchKeyword,
    ClassKeyword,
    ConstKeyword,
    ConstructKeyword,
    ContinueKeyword,
    DataKeyword,
    DefaultKeyword,
    DoKeyword,
    DynamicKeyword,
    ElseKeyword,
    EnumKeyword,
    ExportKeyword,
    FalseKeyword,
    FinallyKeyword,
    FunctionKeyword,
    ForKeyword,
    ForeachKeyword,
    GlobalKeyword,
    IfKeyword,
    ImplKeyword,
    ImportKeyword,
    InKeyword,
    InstanceKeyword,
    IsKeyword,
    LetKeyword,
    LocalKeyword,
    MatchKeyword,
    ModuleKeyword,
    MoveKeyword,
    MutableKeyword,
    OfKeyword,
    ReturnKeyword,
    SelfKeyword,
    StaticKeyword,
    StructKeyword,
    ThenKeyword,
    ThrowKeyword,
    TraitKeyword,
    TrueKeyword,
    TryKeyword,
    TypeKeyword,
    TypeofKeyword,
    VarKeyword,
    WhereKeyword,
    WhileKeyword,
    YieldKeyword,

    // Operators and Symbols
    SingleEqual,
    SemiColon,
    Colon,
    DoubleColon,
    Dot,
    Comma,
    Tilde,
    DoubleEqual,
    ExclamationEq,
    PlusEq,
    MinusEq,
    AsteriskEq,
    SlashEq,
    PercentEq,
    LessThan,
    DoubleLessThan,
    LessThanEq,
    DoubleLessThanEq,
    GreaterThan,
    DoubleGreaterThan,
    GreaterThanEq,
    DoubleGreaterThanEq,
    Plus,
    DoublePlus,
    Minus,
    Asterisk,
    Slash,
    Percent,
    LeftParen,
    RightParen,
    LeftCurly,
    RightCurly,
    LeftBracket,
    RightBracket,
    Exclamation,
    Ampersand,
    AmpersandEq,
    Pipe,
    PipeEq,
    Circumflex,
    CircumflexEq,
    DoubleAmpersand,
    DoublePipe,
    ThickArrow,
    ThinArrow,

    UnexpectedCharacter,
    UnterminatedLiteral,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct Token<'input> {
    pub kind: TokenKind,
    pub text: &'input str,
    pub span: (usize, usize),
}

impl core::fmt::Debug for Token<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "Token({:?}, {:?})",
            self.kind,
            &self.text[self.span.0..self.span.1]
        )
    }
}
